version: '3.0'

services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/tls:/etc/nginx/tls
      - ./public:/public
    ports:
      - "443:443"
    networks:
      isucon12-qualify:
    restart: always

  webapp:
    build: ./webapp/${APP_LANGUAGE:-go}
    environment:
      ISUCON_DB_HOST: mysql
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      ISUCON_ADMIN_HOSTNAME: admin.t.isucon.dev
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./webapp:/home/isucon/webapp
      - tenant_db:/home/isucon/webapp/tenant_db
      - initial_data:/home/isucon/initial_data
      - gopkg:/home/isucon/go/pkg
    init: true
    restart: always
    networks:
      isucon12-qualify:

  mysql:
    image: mysql/mysql-server:8.0.31
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./webapp/sql/admin/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    restart: always
    networks:
      isucon12-qualify:

  blackauth:
    build: ./webapp/go
    ports:
      - "3001:3001"
    init: true
    restart: always
    volumes:
      - .:/home/isucon
    working_dir: /home/isucon/blackauth
    command:
      - /usr/local/go/bin/go
      - run
      - main.go
    networks:
      isucon12-qualify:

  bench:
    build: ./webapp/go
    stdin_open: true
    tty: true
    environment:
      ISUCON_JWT_KEY_FILE: ./isuports.pem
    volumes:
      - .:/home/isucon
      - tenant_db:/home/isucon/webapp/tenant_db
      - initial_data:/home/isucon/initial_data
      - gopkg:/home/isucon/go/pkg
    networks:
      isucon12-qualify:
    working_dir: /home/isucon/bench
    command:
      - "bash"
      - "-c"
      - "sleep infinity"

volumes:
  mysql:
  gopkg:
  tenant_db:
  initial_data:

networks:
  isucon12-qualify:
